name: 🔄 Sync Código a Hugging Face
on:
  push:
    branches: [main]
    # Opcional: Evitar que se active cuando el Bot sube datos
    paths-ignore:
      - 'data/**'
  workflow_dispatch:

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: 🚢 Push Code to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Reemplaza con tu usuario y nombre del Space exactos
          git push --force https://Jose91-BCN:$HF_TOKEN@huggingface.co/spaces/Jose91-BCN/Electricity_demand main
